surging/src/Surging.ApiGateway/Controllers/AuthenticationManageController.cs
using Microsoft.AspNetCore.Mvc;
using Surging.Core.ApiGateWay.ServiceDiscovery;
using Surging.Core.ApiGateWay.Utilities;
using Surging.Core.CPlatform.Address;
using Surging.Core.CPlatform.Utilities;
using System.Linq;
using System.Threading.Tasks;

namespace Surging.ApiGateway.Controllers
{
    public class AuthenticationManageController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> EditServiceToken(string address)
        {
            var list = await ServiceLocator.GetService<IServiceDiscoveryProvider>().GetAddressAsync(address); ;
            return View(list.FirstOrDefault());
        }

        [HttpPost]
        public async Task<IActionResult> EditServiceToken(IpAddressModel model)
        {
           await ServiceLocator.GetService<IServiceDiscoveryProvider>().EditServiceToken(model);
            return Json(ServiceResult.Create(true));
        }
    }
}

surging/src/Surging.ApiGateway/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Surging.ApiGateway.Models;
using System.Diagnostics;

namespace Surging.ApiGateway.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

surging/src/Surging.ApiGateway/Controllers/ServiceManageController.cs
using Microsoft.AspNetCore.Mvc;
using Surging.ApiGateway.Models;
using Surging.Core.ApiGateWay.ServiceDiscovery;
using Surging.Core.ApiGateWay.ServiceDiscovery.Implementation;
using Surging.Core.ApiGateWay.Utilities;
using Surging.Core.Caching.HashAlgorithms;
using Surging.Core.CPlatform;
using Surging.Core.CPlatform.Cache;
using Surging.Core.CPlatform.Support;
using Surging.Core.CPlatform.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Surging.ApiGateway.Controllers
{
    public class ServiceManageController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> GetAddress(string queryParam)
        {
            var list = await ServiceLocator.GetService<IServiceDiscoveryProvider>().GetAddressAsync(queryParam);
            var result = ServiceResult<IEnumerable<ServiceAddressModel>>.Create(true, list);
            return Json(result);
        }

        [HttpPost]
        public async Task<IActionResult> GetServiceDescriptor(string address, string queryParam)
        {
            var list = await ServiceLocator.GetService<IServiceDiscoveryProvider>().GetServiceDescriptorAsync(address, queryParam);
            var result = ServiceResult<IEnumerable<ServiceDescriptor>>.Create(true, list);
            return Json(result);
        }

        public IActionResult ServiceDescriptor(string address)
        {
            ViewBag.address = address;
            return View();
        }

        public IActionResult FaultTolerant(string serviceId, string address)
        {
            ViewBag.ServiceId = serviceId;
            ViewBag.Address = address;
            return View();
        }

        public async Task<IActionResult> EditCacheEndPoint(string cacheId,string endpoint)
        {
            var model = await ServiceLocator.GetService<IServiceCacheProvider>().GetCacheEndpointAsync(cacheId, endpoint);
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> DelCacheEndPoint(string cacheId, string endpoint)
        {
            await ServiceLocator.GetService<IServiceCacheProvider>().DelCacheEndpointAsync(cacheId, endpoint);
            return Json(ServiceResult.Create(true));
        }

        [HttpPost]
        public async Task<IActionResult> EditCacheEndPoint(CacheEndpointParam param)
        {
          await ServiceLocator.GetService<IServiceCacheProvider>().SetCacheEndpointByEndpoint(param.CacheId, param.Endpoint, param.CacheEndpoint);
            return Json(ServiceResult.Create(true));
        }

        public async Task<IActionResult> EditFaultTolerant(string serviceId)
        {
           var  list = await ServiceLocator.GetService<IFaultTolerantProvider>().GetCommandDescriptor(serviceId);
            return View(list.FirstOrDefault());
        }
        
        [HttpPost]
        public async Task<IActionResult> EditFaultTolerant(ServiceCommandDescriptor model)
        {
              await ServiceLocator.GetService<IFaultTolerantProvider>().SetCommandDescriptorByAddress(model);
            return Json(ServiceResult.Create(true));
        }

        [HttpPost]
        public async Task<IActionResult> GetCommandDescriptor(string serviceId, string address)
        {
            IEnumerable<ServiceCommandDescriptor> list = null;
            if (!string.IsNullOrEmpty(serviceId))
            {
                list = await ServiceLocator.GetService<IFaultTolerantProvider>().GetCommandDescriptor(serviceId);
            }
            else if (!string.IsNullOrEmpty(address))
            {
                list = await ServiceLocator.GetService<IFaultTolerantProvider>().GetCommandDescriptorByAddress(address);
            }
            var result = ServiceResult<IEnumerable<ServiceCommandDescriptor>>.Create(true, list);
            return Json(result);
        }

        public IActionResult ServiceCache()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> GetServiceCache(string queryParam)
        {
            var list = await ServiceLocator.GetService<IServiceCacheProvider>().GetServiceDescriptorAsync();
            var result = ServiceResult<IEnumerable<CacheDescriptor>>.Create(true, list);
            return Json(result);
        }

        public  IActionResult ServiceCacheEndpoint(string cacheId)
        {
            ViewBag.CacheId = cacheId;
            return View();
        }

        public async Task<IActionResult> GetCacheEndpoint(string cacheId)
        {
            var list = await ServiceLocator.GetService<IServiceCacheProvider>().GetCacheEndpointAsync(cacheId);
            var result = ServiceResult<IEnumerable<CacheEndpoint>>.Create(true, list);
            return Json(result);
        }


        public IActionResult ServiceSubscriber(string serviceId)
        {
            ViewBag.ServiceId = serviceId;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> GetSubscriber(string queryParam)
        {
            var list = await ServiceLocator.GetService<IServiceSubscribeProvider>().GetAddressAsync(queryParam);
            var result = ServiceResult<IEnumerable<ServiceAddressModel>>.Create(true, list);
            return Json(result);
        }
    }
}

surging/src/Surging.ApiGateway/Views/Home/Index.cshtml
@{
    ViewBag.Title = "首页";
    var isPjax = !string.IsNullOrEmpty( Context.Request.Headers["X-PJAX"]) && bool.Parse(Context.Request.Headers["X-PJAX"]);
    Layout = isPjax ? null : "~/Views/Shared/_ManagerLayout.cshtml";
}
<div class="pc-wrapper">
    <div id="main">
        <div class="pc-index">
            <div class="index-wrap">
                <div class="index-wrap-inner">
                    <h3 class="index-head">运行概况</h3>
                    <div class="alert alert-block alert-point">
                        <button type="button" class="close" data-dismiss="alert">
                            <i class="icon-remove"></i>
                        </button>

                        <i class="icon-ok green"></i>

                        欢迎使用
                        <strong class="green">
                            Surging Gateway<small>(v0.14)</small>
                        </strong>,基于.NET CORE Surging微服务网关
                    </div>
                </div>
            </div>
        </div>

    </div>
    <div class="pc-app">
        <!--<a class="back-home" style="color:#5891aa" href="/PersonalCenter/view/work/index.shtml" data-pjax="#wrapper" data-mode="appsHome"><i class="surging-icon-left"></i><span>展开应用</span></a>-->
        <div class="app-wrap">
            <a class="pc-app-btn pc-app-monitor" href="javascript:;" data-mode="apps" data-pjax="#app_wrap"><i class="app-icon"></i></a>
            <a class="pc-app-btn pc-app-service" href="@Url.Action("Index","ServiceManage")" data-mode="apps" data-pjax="#app_wrap"><i class="app-icon"></i></a>
            <a class="pc-app-btn pc-app-defend" href="javascript:;" data-mode="apps" data-pjax="#app_wrap"><i class="app-icon"></i></a>
            <a class="pc-app-btn pc-app-identity" href="@Url.Action("Index","AuthenticationManage")" data-mode="apps" data-pjax="#app_wrap"><i class="app-icon"></i></a>
            <a class="pc-app-btn pc-app-flowrate " href="javascript:;" data-mode="apps" data-pjax="#app_wrap"><i class="app-icon"></i></a>
            <a class="pc-app-btn pc-app-diversion" href="javascript:;" data-mode="apps" data-pjax="#app_wrap"><i class="app-icon"></i></a>
        </div>
    </div>
</div>
@section FootJS
    {

}